export const productTypesOptions = [
    { value: "tablet", label: "Tablet" },
    { value: "capsule", label: "Capsule" },
    { value: "syrup", label: "Syrup" },
    { value: "ointment", label: "Ointment" },
    { value: "injection", label: "Injection" },
    { value: "suspension", label: "Suspension" },
    { value: "cream", label: "Cream" },
    { value: "gel", label: "Gel" },
  ];

  export const mgOptions = [
    { value: "0.25mg", label: "0.25mg" },
    { value: "0.5mg", label: "0.5mg" },
    { value: "1mg", label: "1mg" },
    { value: "2mg", label: "2mg" },
    { value: "2.5mg", label: "2.5mg" },
    { value: "2.5mg + 500mg", label: "2.5mg + 500mg" },
    { value: "2.5mg + 850mg", label: "2.5mg + 850mg" },
    { value: "2.6mg", label: "2.6mg" },
    { value: "4mg", label: "4mg" },
    { value: "5mg", label: "5mg" },
    { value: "7.5mg", label: "7.5mg" },
    { value: "5mg + 20mg", label: "5mg + 20mg" },
    { value: "5mg + 40mg", label: "5mg + 40mg" },
    { value: "5mg + 80mg", label: "5mg + 80mg" },
    { value: "8mg", label: "8mg" },
    { value: "10mg", label: "10mg" },
    { value: "10mg + 100mg", label: "10mg + 100mg" },
    { value: "12.5mg + 50mg", label: "12.5mg + 50mg" },
    { value: "12.5mg + 5g", label: "12.5mg + 5g" },
    { value: "20mg", label: "20mg" },
    { value: "25mg", label: "25mg" },
    { value: "30mg", label: "30mg" },
    { value: "35mg", label: "35mg" },
    { value: "40mg", label: "40mg" },
    { value: "50mg", label: "50mg" },
    { value: "50mg + 500mg", label: "50mg + 500mg" },
    { value: "50mg + 850mg", label: "50mg + 850mg" },
    { value: "75mg", label: "75mg" },
    { value: "80mg", label: "80mg" },
    { value: "75mg + 75mg", label: "75mg + 75mg" },
    { value: "90mg", label: "90mg" },
    { value: "100mg", label: "100mg" },
    { value: "120mg", label: "120mg" },
    { value: "180mg", label: "180mg" },
    { value: "200mg", label: "200mg" },
    { value: "210mg", label: "210mg" },
    { value: "400mg", label: "400mg" },
    { value: "500mg", label: "500mg" },
    { value: "565mg", label: "565mg" },
    { value: "565mg", label: "565mg" },
    { value: "660mg", label: "660mg" },
    { value: "1gm", label: "1gm" },
  ];

  export const mlOptions = [
    { value: "10ml", label: "10ml" },
    { value: "25ml", label: "25ml" },
    { value: "50ml", label: "50ml" },
    { value: "100ml", label: "100ml" },
    { value: "200ml", label: "200ml" },
  ];

  export const ampouleOptions = [
    { value: "1 ampoule", label: "1 Ampoule" },
    { value: "2 ampoules", label: "2 Ampoules" },
    { value: "5 ampoules", label: "5 Ampoules" },
  ];